Update package tags script
storybookjs/frontpage pull request #657
Opened 2024-01-25 18:47 UTC by kylegach

- Append for `add` command
- Add package disallow list

2024-01-26 17:34 UTC, jonniebigodes requested changes
@kylegach, thanks for putting this together; however, there's a bit of an issue, and you might have more context. I ran a couple of tests, and it worked out. Nonetheless, after checking the preview deployment, I noticed some issues. Here's what I did:
- Opened up the preview deploy
- Went to the documentation and selected the 8.0 docs
- Started vetting the documentation and noticed that on these pages:
  - [Test coverage](https://deploy-preview-657--storybook-frontpage.netlify.app/docs/8.0/writing-tests/test-coverage)
  - [Install addons](https://deploy-preview-657--storybook-frontpage.netlify.app/docs/8.0/addons/install-addons)
  - [Webpack](https://deploy-preview-657--storybook-frontpage.netlify.app/docs/8.0/builders/webpack)

The next specifier was applied to the snippets, as you can see:
 
![coverage-addon-issue](https://github.com/storybookjs/frontpage/assets/22988955/bf3c75da-43ae-461e-9010-bced4a882d03)

![issue-addon-installation-guide](https://github.com/storybookjs/frontpage/assets/22988955/1d0d2e1a-2fa8-434e-912b-39095537ff6d)

![issue-snippet-builders-webpack](https://github.com/storybookjs/frontpage/assets/22988955/bb85036f-b57a-43eb-89bb-a21352f0fc15)

This type of issue will become a bit more apparent with the CLI versioning that is being worked on, and we should consider this scenario to avoid misleading the users as the Storybook CLI is showcasing `latest` and the addon version will be the version on `next`. Let me know, and we'll take it from there.

2024-01-26 19:05 UTC, kylegach commented
@jonniebigodes —

> - Opened up the preview deploy
> - Went to the documentation and selected the 8.0 docs

The deploy preview only works with the latest version. All of the other versions, like `8.0`, are actually separate sites that are stitched together to appear as one. So as soon as you switched versions, you were no longer on the deploy preview, but the production site (albeit under the deploy preview URL, which is admittedly confusing).

The test suite attempts to ensure that the behavior for both "latest" and "next" builds will be correct.

2024-01-26 19:11 UTC, jonniebigodes approved these changes

2024-01-26 19:11 UTC, merged

2024-01-29 19:42 UTC, kylegach commented
Follow-up:

- Manipulate `remove` command instances
- Docs repercussions of https://github.com/storybookjs/storybook/issues/25790